# -*- coding: utf-8 -*-
"""
Created on 2022-11-07 15:19:32
---------
@summary:
---------
@author: 逢高SAMA
"""

from feapder import Item


class EuropeanUnionDataItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i european_union_data
    """

    __table_name__ = "european_union_data"

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.type = None  # 类目
        self.scope = None  # 筛选条件
        self.res_url = None  # response_url
        self.uuid = None  # 查询条件uuid
        self.json_data = None  # 结果数据/json格式
        # self.date = None  # 数据插入时间
